name: Build & Publish testing pulsar cloud image

on:
  workflow_dispatch:
    inputs:
      pulsar_cloud_tag:
        description: pulsar cloud docker image with tag
        required: true
envs:
  PULSAR_CLOUD_TAG: ${{ github.event.inputs.pulsar_cloud_tag }}
  PULSAR_CLOUD_IMAGE: docker.cloudsmith.io/streamnative/cloud-pulsar/pulsar-cloud:${{ github.event.inputs.pulsar_cloud_tag }}

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: mvn clean install -DskipTests
      - name: Extract Maven project version
        run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        id: version
      - uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        envs:
          OXIA_VERSION: ${{ steps.version.outputs.version }}
        with:
          context: .
          platforms: linux/x86_64,linux/arm64
          push: true
          file: {context}/.ci/Dockerfile
          tags: streamnative/pulsar-cloud:$PULSAR_CLOUD_TAG-oxia-$OXIA_VERSION
          build-args:
            PULSAR_CLOUD: $PULSAR_CLOUD_IMAGE
            OXIA_VERSION: $OXIA_VERSION